version: '3.8'

services:
  bot:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data

